version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building a Docker image for frontend"
      - docker build -t $ECR_REPOSITORY_FRONTEND_URL:latest -f frontend/Dockerfile frontend

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the frontend Docker image..."
      - docker push $ECR_REPOSITORY_FRONTEND_URL:latest
      - echo "Writing image definitions file for ECS deployment..."
      - printf '[{"name":"frontend","imageUri":"%s"}]' $ECR_REPOSITORY_FRONTEND_URL:latest > imagedefinitions.json
      - echo Contents of imagedefinitions.json:
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  name: image_definitions

cache:
  paths:
    - /root/.cache/pip
    - /root/.npm
