"""add knowledgebase_id column to project table

Revision ID: 96986b650a5c
Revises: 58842de7cb9e
Create Date: 2025-03-31 14:02:11.533525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96986b650a5c'
down_revision: Union[str, None] = '58842de7cb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('knowledgebase_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'knowledgebase_id')
    # ### end Alembic commands ###
